# Generated by Django 4.2.4 on 2023-08-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedaudio',
            old_name='uploaded_at',
            new_name='upload_date',
        ),
        migrations.AddField(
            model_name='uploadedaudio',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedaudio',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadedaudio',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
