# Generated by Django 4.2.4 on 2023-08-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0002_rename_uploaded_at_uploadedaudio_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedaudio',
            name='audio_file',
            field=models.FileField(upload_to=''),
        ),
    ]
